Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'Networkteam.Neos.PencilCase:PencilCase':
            resource: resource://Networkteam.Neos.PencilCase/Public/PencilCase/Plugin.js
        stylesheets:
          'Networkteam.Neos.PencilCase:PencilCase':
            resource: resource://Networkteam.Neos.PencilCase/Public/PencilCase/Plugin.css
      frontendConfiguration:
        Networkteam.Neos.PencilCase:
          headingOptions: # present dropdown in ckeditor toolbar, Heading 1, Paragraph, Pre etc.
            fancy:
              label: Fancy
              tagName: span
              attributes:
                class: fancy
                data-nwt-plugin: nwt.awesomeSpecialTextEffect
                styles:
                  color: tomato
          customOptions:
            violet:
              tooltip: Highlight
              icon: rocket
              tagName: span
              attributes:
                class: 'highlight'
                styles:
                  background: violet
              editableAttributes:
                id: true
                data-test: true
                title: true
