Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'Networkteam.Neos.PencilCase:PencilCase':
            resource: resource://Networkteam.Neos.PencilCase/Public/PencilCase/Plugin.js
      frontendConfiguration:
        Networkteam.Neos.PencilCase:
          fancy: true
