Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'Networkteam.Neos.PencilCase:PencilCase':
            resource: resource://Networkteam.Neos.PencilCase/Public/PencilCase/Plugin.js
      frontendConfiguration:
        Networkteam.Neos.PencilCase:
          style: # present dropdown in ckeditor toolbar, Heading 1, Paragraph, Pre etc.
            fancy:
              title: 'Fancy'
              element: 'span'
              attributes:
                class: 'fancy'
                data-nwt-plugin: 'nwt.awesomeSpecialTextEffect'
                style: 'color: tomato;'
          buttons:
            violet:
              title: Highlight
              element: span
              attributes:
                class: 'highlight'
